Fixes ros-noetic-arch/ros-noetic-moveit-setup-assistant#3
ros-noetic-arch/ros-noetic-moveit-setup-assistant pull request #4
Opened 2022-07-14 20:35 UTC by AM4283

This should fix the build issue, package installed correctly after applying this patch

Patches #3

2022-07-14 20:48 UTC, acxz requested changes
Sweet, glad you got to the bottom of this!

Can you update the pkgrel and the .SRCINFO as well? See: https://wiki.archlinux.org/title/PKGBUILD#pkgrel and https://wiki.archlinux.org/title/.SRCINFO

Also can you make a pull request to upstream and then change the source to point to the PR instead.

Can you also change the commit message to be like so:
`git commit -m "upgpkg: ros-noetic-moveit-setup-assistant 1.1.8-4" -m "apply patch for proper bool type"`

2022-07-14 23:26 UTC, AM4283 commented
Ok should be done now!

2022-07-15 00:39 UTC, acxz requested changes

2022-07-15 00:39 UTC, acxz commented on PKGBUILD
> +source=("${pkgname}-${pkgver}.tar.gz"::"https://github.com/ros-planning/moveit/archive/${pkgver}.tar.gz" "fixbuild.patch"::"https://patch-diff.githubusercontent.com/raw/ros-planning/moveit/pull/3175.
just a nit, can you put the patch source on the next line to keep it consistant

2022-07-15 00:39 UTC, acxz commented on .SRCINFO
> +	source = build.patch::https://patch-diff.githubusercontent.com/raw/ros-planning/moveit/pull/3175.patch
Looks like you need to run `makepkg --printsrcinfo > .SRCINFO` again, the source (build.patch) name is different from the one in PKGBUILD (fixbuild.patch)

2022-07-15 00:39 UTC, acxz commented on fixbuild.patch
> +diff --unified --recursive --text moveit-1.1.8/moveit_setup_assistant/src/tools/moveit_config_data.cpp moveit-1.1.8.new/moveit_setup_assistant/src/tools/moveit_config_data.cpp
You can delete this, since the patch source is obtained online.

2022-07-15 00:39 UTC, acxz commented
The AUR will only accept one commit per update, can you squash your commits into one?

2022-07-16 21:52 UTC, acxz commented
@AM4283 can you follow up on the comments?

2022-07-20 19:27 UTC, AM4283 commented
> @AM4283 can you follow up on the comments?

Sorry, haven't been active on my personal GitHub in a bit. Hopefully this is good? This is the first time I've squashed commits before like this so I'm not sure if I did it exactly right.

2022-07-20 19:31 UTC, acxz commented
I'm afraid you seem to have added commits instead of squashed them. I recommend using the `git rebase -i` command.

2022-07-21 22:01 UTC, acxz commented
If you want we can get on call to work this out together, or you can give me write access to your fork and I can fix it myself.

2022-07-21 22:15 UTC, closed without merging

2022-07-21 22:20 UTC, acxz commented
closed with [104f592](https://github.com/ros-noetic-arch/ros-noetic-moveit-setup-assistant/commit/104f59217b0db7d819c56594f6dd71f333962625)

Sorry @AM4283 thought it would easier if I just pulled in the commit myself. But we got your commit in! Thanks for the contribution!